export * from './url.config'
export * from './api.config'
export * from './path-labels.config'
export * from './admin-menu.config'
export { getNavMenu } from '@/config/nav-menu'
export { getDictionaryMenu } from '@/config/dictionary-menu'
